# start of Meshtastic configure yaml
canned_messages: Hi|Bye|Yes|No|Ok
channel_url: https://meshtastic.org/e/#CgcSAQE6AggNEhsIARAFGPoBIAsoBTgDQARIAVAUaAHABgHIBgE
config:
  bluetooth:
    enabled: false
    fixedPin: 123456
    mode: FIXED_PIN
  device:
    nodeInfoBroadcastSecs: 3600
  display:
    screenOnSecs: 600
  lora:
    bandwidth: 250
    codingRate: 5
    configOkToMqtt: true
    hopLimit: 4
    ignoreMqtt: true
    modemPreset: SHORT_SLOW
    region: EU_868
    spreadFactor: 11
    sx126xRxBoostedGain: true
    txEnabled: true
    txPower: 20
    usePreset: true
  network:
    ntpServer: meshtastic.pool.ntp.org
  position:
    broadcastSmartMinimumDistance: 100
    broadcastSmartMinimumIntervalSecs: 30
    fixedPosition: true
    gpsMode: NOT_PRESENT
    gpsUpdateInterval: 120
    positionBroadcastSecs: 900
    positionBroadcastSmartEnabled: false
    positionFlags: 811
  power:
    deviceBatteryInaAddress: 65
    lsSecs: 300
    minWakeSecs: 10
    sdsSecs: 4294967295
    waitBluetoothSecs: 60
  security:
    privateKey: base64:mAuDcjkNTF9VOXnP0Jwon/SPZ/WhGhtBCXL+32lPtG0=
    publicKey: base64:agdgiV6DEotQTomLIhMVaKjJsJ0UXHWg65C2QIzdZmM=
    serialEnabled: true
location:
  lat: 56.0201728
  lon: 6.0030976
module_config:
  ambientLighting:
    blue: 76
    current: 10
    green: 145
    red: 168
  cannedMessage:
    enabled: true
  detectionSensor:
    detectionTriggerType: LOGIC_HIGH
    minimumBroadcastSecs: 45
  mqtt:
    address: mqtt.meshtastic.org
    encryptionEnabled: true
    password: large4cats
    root: msh/EU_868
    username: meshdev
  neighborInfo:
    enabled: true
    updateInterval: 21600
  telemetry:
    deviceUpdateInterval: 3600
    environmentMeasurementEnabled: true
    environmentUpdateInterval: 3600
    powerMeasurementEnabled: true
    powerUpdateInterval: 3600
owner: =[Please Change]=
owner_short: '0000'


